spring:
  application:
    name: zuul-gateway

server:
  port: 9000

# 指定注册的服务中心地址，一般与eureka-server中配置的对应，此时该服务启动就会将自己注册到服务中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# zuul的相关配置
zuul:
  prefix: /changlu   # 访问zuul网关的前缀url（由原来的/ => /changlu）
  routes:            # 路由配对，下面有两组服务
    course-list:
      path: /list/**             # 2、指定的服务路由转换 (例如由原来的/course-list => /list)
      service-id: course-list    # 1、指定的服务名(application name)：课程服务
    course-price:
      path: /price/**
      service-id: course-price