# 图片文件上传
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

# 阿里云OSS配置
aliyun:
  oss:
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:   # 桶名称
    key:     # 存储根路径