server:
  port: 8000
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false  #fetch-registry：获取注册表。不需要同步其他节点数据。（当前没有建立eureka server集群，这里不需要同步节点）
    register-with-eureka: false  # 代表是否将自己也注册到Eureka Server，这里不注册
    service-url:  # 设置服务的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
