server:
  port: 8081

spring:
  application:
    name: consumer
  rabbitmq:
    addresses: 192.168.118.128:5672
    username: admin
    password: password
    virtual-host: /
    connection-timeout: 15000
