server:
  port: ${SERVER_PORT:81}   # 默认是81端口，可以通过命令行读取参数 -DSERVER_PORT=82

spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 123456
  cloud:
    gateway:
      enabled: true   # 默认开启，只要加了网关依赖
      routes:
          # 用户服务路由
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/user
          # 登录服务路由
        - id: login-service-route
#          uri: http://localhost:8081  # uri
          uri: lb://login-service   # 实现负载均衡
          predicates:
            - Path=/doLogin  # 匹配路径规则 只要你Path匹配上了/doLogin 就往 uri 转发 并且将路径带上
            - After=2022-07-29T16:23:21.719+08:00[Asia/Shanghai] #此断言匹配发生在指定 日期时间之后的请求，ZonedDateTime dateTime=ZonedDateTime.now()获得
            - name: CheckAuth #自定义路由断言工厂的名称xxxRoutePredicateFactory，这个xxx就是在这里指明
              args:
                name: changlu  #传入到自定义路由断言工厂的参数
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@apiKeyResolver}'
                redis-rate-limiter.replenishRate: 1 #令牌每秒填充速度
                redis-rate-limiter.burstCapacity: 1 #桶大小
                redis-rate-limiter.requestedTokens: 1 #默认是1，每次请求消耗的令牌数
      # 服务发现相关配置
      discovery:
        locator:
          enabled: true   # 开启动态路由  开启通用应用名称 找到服务的功能
          lower-case-service-id: true  # 开启服务名称小写，因为在eureka中默认服务名是大写的


# 配置eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}

